version: '3.7'

services:
  puppeteer:
    container_name: example-puppeteer-jest
    image: lecaoquochung/puppeteer:dev
    init: true
    tty: true
    stdin_open: true
    volumes:
      - ./:/code
    working_dir: /code
    env_file:
      - .env
    dns: 8.8.8.8
    entrypoint: ["sh", "-c", "sleep infinity"]