version: 2
jobs:
  build:
    docker:
      - image: lecaoquochung/puppeteer:dev
        user: pptruser
        environment:

    working_directory: ~/code

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1.0.1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1.0.1-dependencies-

      # env
      - run: 
          name: Before
          command: |
            pwd;ls;whoami

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1.0.1-dependencies-{{ checksum "package.json" }}
        
      - run: 
          name: Jest test
          command: 
            yarn test
      
      - run:
          name: Cucumber test
          command:
            yarn cucumber

      - run:
          name: Cucumber report
          command:
            yarn test:report